### ISSUE TITLE
Add "About" and "Help" items in navbar for beta pages

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#219]
For homepage, this should look like:
![navbar-update-homepage](https://cloud.githubusercontent.com/assets/4512335/8710077/04936c84-2b15-11e5-8b2b-8c053e694987.png)

For all other pages (search results page, article page, profile page), this should look like:
![navbar-update-article-page](https://cloud.githubusercontent.com/assets/4512335/8710090/167cdff2-2b15-11e5-9a8a-d15a371dc4d2.png)

"About" should display all of the information from the alpha landing page (https://curatescience.org/; though without the landing page navbar of course), but display the info within the beta page.

"Help" will be a drop-down menu:
"How-To..." and "FAQ" will display the information from this mockup html page I just created, see the "help.html" file within this .zip file (https://dl.dropboxusercontent.com/u/227724/help-page.zip) (I basically stole the code from the FAQ section of the landing page). 

"How-To..." should link to the top section (id="section-1") of help.html
"FAQ" should link to the second section (id="section-2") of help.html
"Contact" should simply link to "contact@curatescience.org"

**Comment by alexkyllo** [comment]
Making good progress on this. I set up the menu and routing, now all that's left for me to do is merge the content of help.html into the new HelpPage.js. I think I'll be able to finish within this weekend.

**Comment by alexkyllo** [comment]
Ok, I'm ready to deploy this to staging. There is one issue, [m.route](https://lhorie.github.io/mithril/mithril.route.html) uses the hash (#) symbol for URL routing, which breaks named anchors (e.g. "/help/#section-1" doesn't work).

**Comment by eplebel** [comment]
Looks great overall, however, here are two issues i've identified so far:
(1)  The about page doesn't seem to have been updated to displaying all of the info on the landing page (https://curatescience.org/); it still is just displaying the about section from the landing page
(2) If you log out and log back in, the images within the How-to section are not displaying:
![images-issues](https://cloud.githubusercontent.com/assets/4512335/8896492/74adb672-33cc-11e5-9f9b-369ac4f38be0.png)

**Comment by alexkyllo** [comment]
Ok I will figure out what's going on and fix it tonight

**Comment by alexkyllo** [comment]
I fixed the issue with the broken links and just pushed to staging.
As for the About page--it's not as simple as just copying over the content--it will take a while to make it look nice due to the CSS differences (alpha page uses bootstrap, beta page doesn't). Do you want everything down to the bottom copied over, including the Team photos? I'm not sure if I understand why you want the same content on the Alpha page copied to the Beta page--are you planning to get rid of the Alpha page at some point?

**Comment by eplebel** [comment]
> I'm not sure if I understand why you want the same content on the Alpha page copied to the Beta page--are you planning to get rid of the Alpha page at some point?

My thinking is that if people are accessing an article page directly from a link shared on Twitter (e.g., https://www.curatescience.org/beta/#/articles/335262), and then click on "About" to learn more about Curate Science, they should be ables to see all of the information about Curate Science without having to manually go to the landing page. Makes sense?

**Comment by eplebel** [comment]
Actually, I just realized a simple solution for this would just be to add a sentence at the end of that section that says: "For more details about Curate Science, please go here", with the "here" hyperlinked to the current landing page (https://curatescience.org).

**Comment by eplebel** [comment]
Also, as a solution to the m.route issue you mentioned July 26, I can just combine these two into one menu item as "How-To / FAQ", and then it should be obvious to users that they have to scroll down to see the FAQ. 

I'm going to try and make those changes and then we can close this issue! (and then we can focus on other more important issues remaining for public beta , that is, https://github.com/ScienceCommons/api/labels/public%20beta)!

**Comment by eplebel** [comment]
OK I just addressed the beta about section with the following changes (https://github.com/ScienceCommons/www/commit/690be9ae9efa0cadcb2a77e451dda51b80c05ee7).

However, for combining the "How-To" and "FAQ" menu items, I looked into it and it seemed too complicated (and didn't want to break anything), so I decided against trying to address it. 

So at your earliest convenience, you can go ahead and make that change and then we can close this issue!

**Comment by alexkyllo** [comment]
Ok, I consolidated the How-To and FAQ items in the Help Menu. 
Committed to staging: https://github.com/ScienceCommons/www/commit/9d042a00da5d4152accbddcdb9b6ffcc12fd0bba
Pull request opened: https://github.com/ScienceCommons/www/pull/42
